### PR TITLE
Revert config change, disable CONFIG_P2P breaking AP mode 

### PR DESCRIPTION
**Pull request by LaakkonenJussi**
The P2P breaks AP mode, all others seemed to work fine. This means WiFi Direct is not going to work and kernel configs provided no further insight. Maybe C2 driver is not supporting something needed for this.

### CODE REVIEW

**Review by Thaodan — APPROVED** [review]
LGTM

**Review by spiiroin — APPROVED** [review]

**Comment by pvuorela** [comment]
Could we just keep having a config that defines the meaningful adjustments to default config we want? If the old version had some adjustments we still want, those can be added separately.

The default config with some adjustments on top of it is noisy and it's still problematic with version updates. Doing the update right should basically require copying even the comment adjustments to the config, but then again not reverting any comment change we've done on purpose.

Edit: ...and actually this is probably missing now the upstream changes to the default config file after the last update.

**Comment by Thaodan** [comment]
Another option would be to patch the upstream config with our changes similarly as fedora does. We would get the benefit of the upstream comments in the config with our changes without having to manually rebase the config on each update.
The downside is that the changes are not as readable as you can't see the configuration in context to the rest of configuration that changes.
Sadly there's no documentation to the configuration options outside of the upstream config. The system looks like a Kconfig style system without the documentation it brings.

**Comment by LaakkonenJussi** [comment]
Well at least we have some documentation of the config options, which in general is a lot better than a plain file with only the options there. Every time we update we should, at least from now on, really test the effect of some new suggested options and only after that add them to the end.

Or we just use the default configuration and then patch it, which is also cumbersome. In old config we had short oneliners that "does not build". Really informative, maybe this way we end up building more informative configuration that has the necessary information on why we use or skip certain options.

**Pull request merged**
